// Generated by CoffeeScript 1.3.1
(function() {

  describe('ToDo', function() {
    var testData;
    testData = [
      {
        "text": "new Todo",
        "done": false
      }, {
        "text": "new Todo 2",
        "done": true
      }
    ];
    return describe('TodoCtrl', function() {
      var $httpBackend, ctrl, scope;
      scope = null;
      ctrl = null;
      $httpBackend = null;
      beforeEach(function() {
        module('todoApp');
        return inject(function(_$httpBackend_, $rootScope, $controller) {
          $httpBackend = _$httpBackend_;
          scope = $rootScope.$new();
          scope.todos = [];
          $httpBackend.expectGET('proxy.php').respond(testData);
          return ctrl = $controller('TodoCtrl', {
            $scope: scope
          });
        });
      });
      it('should todos at start will be empty', function() {
        expect(scope.todos).toBeDefined();
        return expect(scope.url).toEqual('proxy.php');
      });
      it('get all', function() {
        scope.getAll();
        $httpBackend.flush();
        return expect(scope.todos).toEqual(testData);
      });
      return it('remaining', function() {
        var count;
        scope.todos = testData;
        count = scope.remaining();
        return expect(count).toEqual(1);
      });
    });
  });

}).call(this);
