// Generated by CoffeeScript 1.3.3
(function() {

  describe('ToDo', function() {
    var newTodo, testData;
    testData = [
      {
        "text": "new Todo",
        "done": false
      }, {
        "text": "new Todo 2",
        "done": true
      }
    ];
    newTodo = [
      {
        "id": 1111,
        "text": "new test Todo",
        "done": false
      }
    ];
    return describe('TodoCtrl', function() {
      var $httpBackend, ctrl, scope;
      scope = null;
      ctrl = null;
      $httpBackend = null;
      beforeEach(function() {
        module('todoApp');
        return inject(function(_$httpBackend_, $rootScope, $controller) {
          $httpBackend = _$httpBackend_;
          scope = $rootScope.$new();
          scope.todos = [];
          ctrl = $controller('TodoCtrl', {
            $scope: scope
          });
        });
      });
      it('should todos at start will be empty', function() {
        expect(scope.todos).toBeDefined();
        return expect(scope.url).toEqual('proxy.php');
      });
      it('get all', function() {
        $httpBackend.expectGET('proxy.php').respond(testData);
        scope.getAll();
        $httpBackend.flush();
        return expect(scope.todos).toEqual(testData);
      });
      it('remaining', function() {
        var count;
        scope.todos = testData;
        count = scope.remaining();
        return expect(count).toEqual(1);
      });
      it('archive', function() {
        scope.todos = testData;
        scope.archive();
        return expect(scope.todos.length).toEqual(1);
      });
      return it('add todo', function() {
        $httpBackend.expectPOST('proxy.php').respond(newTodo);
        scope.todos = testData;
        scope.todoText = "new test Todo";
        scope.addTodo();
        $httpBackend.flush();
        return expect(scope.todos.length).toEqual(3);
      });
    });
  });

}).call(this);
